name: Scan for Critical Vulnerabilities and Generate GitHub Issue
on: push
jobs:
  vuln-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --json-file-output=critical_vuln_scan.json --severity-threshold=critical
      - name: Checkout Repository
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.13
      - name: Install dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_SECRET }}
          GITHUB_REPO: ${{ github.GITHUB_REPO }}
          VULN_SCAN_FILE: "critical_vuln_scan.json"
        run: |
          python -m pip install --upgrade pip
          pip install requests
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Execute Issue Checking Script
        run: python create_github_issue.py